---
title: "Graphics with ggplot2"
author: "Ingrid"
date: "March 12, 2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Learning ggplot2

```{r}
library(tidyverse)
library(ggthemes)
```

```{r}
mpg

```

```{r}
my_plot <- ggplot(data = mpg, mapping =aes(x= displ, y = hwy))
my_plot + geom_point(alpha = 0.4)
```
```{r}
ggplot(mpg,aes(x=displ, y= hwy, color = class)) +
  geom_point()
```
Make a scatterplot of `hwy` vs `cty` with different sized points representing each `class` and different colors for each fuel type (`fl`)

```{r}
ggplot(mpg, aes(x = hwy, y = cty, size = class, color = fl)) +
  geom_point()

```
```{r}
ggplot(mpg,aes(x=displ, y= hwy)) +
  geom_point(alpha = 0.4, color = "blue")
```

```{r}
ggplot(mpg,aes(x=displ, y= cty, color = class)) +
  geom_point() +
  facet_wrap(~ manufacturer, ncol=5) +
theme_bw()
```

```{r}
ggplot(mpg,aes(x=drv, y= hwy)) +
  geom_violin() 
 
```
```{r}
ggplot(mpg,aes(x=displ, y= hwy)) +
  geom_point() +
  geom_smooth() +
labs(title = "Engine size and highway mileage (mpg)" ,
     x = "Engine size (liters displaced)",
     y = "Highway mileage (mpg)")

```
```{r}
myplot <- ggplot(mpg, aes(x= fl, fill = class)) +
  geom_bar(position = "dodge")

ggsave("example_plot.png", plot = myplot, width = 15, height = 15, units = 'cm')
```

